# based on `https://github.com/purrbot-site/Docs/blob/master/.github/workflows/deploy.yml`
name: Deploy Site

on:
  push:
    branches:
      - main
    paths:
      - "doc/**"
      - ".github/workflows/deploy.yml"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Chekout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ">=3.8"

      - name: Install dependencies
        run: |
          cd doc
          python -m pip install --upgrade pip setuptools mkdocs
          mkdocs get-deps >>requirements.txt
          python -m pip install -r requirements.txt

      - name: Configure GitHub Pages
        id: configure-pages
        uses: actions/configure-pages@v5

      - name: Build documentation
        env:
          REPO_URL: https://github.com/${{ github.repository }}/
          SITE_URL: ${{ steps.configure-pages.outputs.base_url }}
        run: |
          cd doc
          mkdocs build -sv

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: "doc/site/"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
